# Generated by Django 3.2.9 on 2021-11-28 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodmainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default=1, upload_to='', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
